{% extends "generic.html" %}

{% block header %}
{{ entry.title }}
{% endblock %}

{% load staticfiles %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% block content %}
<p>DISCLAIMER: Don't know how to solve this, but removing /usr/bin/lsb_release got rid of the error.<br /><br />
This post has some notes on my exploration of a linux/python environment error. I have no idea when/how 'lsb_release' was installed (I assume during an update/upgrade of some kind), but both apt-get and python would return erros.</p>
<h3>Error Message</h3>
<pre><code class="bash">$ sudo python3 -m pip install django
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.5/site-packages/pip/commands/install.py", line 272, in run
    with self._build_session(options) as session:
  File "/usr/lib/python3.5/site-packages/pip/basecommand.py", line 72, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/usr/lib/python3.5/site-packages/pip/download.py", line 329, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/lib/python3.5/site-packages/pip/download.py", line 93, in user_agent
    from pip._vendor import distro
  File "/usr/lib/python3.5/site-packages/pip/_vendor/distro.py", line 1050, in <module>
    _distro = LinuxDistribution()
  File "/usr/lib/python3.5/site-packages/pip/_vendor/distro.py", line 594, in __init__
    if include_lsb else {}
  File "/usr/lib/python3.5/site-packages/pip/_vendor/distro.py", line 931, in _get_lsb_release_info
    raise subprocess.CalledProcessError(code, cmd, stdout, stderr)
subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.5/site-packages/pip/__main__.py", line 19, in <module>
    sys.exit(pip.main())
  File "/usr/lib/python3.5/site-packages/pip/__init__.py", line 249, in main
    return command.main(cmd_args)
  File "/usr/lib/python3.5/site-packages/pip/basecommand.py", line 251, in main
    timeout=min(5, options.timeout)) as session:
  File "/usr/lib/python3.5/site-packages/pip/basecommand.py", line 72, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/usr/lib/python3.5/site-packages/pip/download.py", line 329, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/lib/python3.5/site-packages/pip/download.py", line 93, in user_agent
    from pip._vendor import distro
  File "/usr/lib/python3.5/site-packages/pip/_vendor/distro.py", line 1050, in <module>
    _distro = LinuxDistribution()
  File "/usr/lib/python3.5/site-packages/pip/_vendor/distro.py", line 594, in __init__
    if include_lsb else {}
  File "/usr/lib/python3.5/site-packages/pip/_vendor/distro.py", line 931, in _get_lsb_release_info
    raise subprocess.CalledProcessError(code, cmd, stdout, stderr)
subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 1</code></pre>
<h3>My System</h3>
<p>Ubuntu Subsystem/Python3</p>
<pre><code class="bash">$ uname -a
Linux (name) 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
$ python3 --version
Python 3.5.4 :: Continuum Analytics, Inc.</code></pre>
<h3>What/Where</h3>
<p><a href="https://refspecs.linuxfoundation.org/LSB_3.0.0/LSB-PDA/LSB-PDA/lsbrelease.html">lsb_release</a>
- prints certain LSB (Linux Standard Base) and Distribution information.</p>
<pre><code class="bash">$ whereis lsb_release
lsb_release: /usr/bin/lsb_release /usr/share/man/man1/lsb_release.1.gz
(python script)

$ python3 -m pip list
(no lsb_release)

$ python3 -m conda list
(no lsb_release)

$ /usr/bin/lsb_release
Traceback (most recent call last):
  File "./lsb_release", line 25, in <module>
    import lsb_release
ImportError: No module named 'lsb_release'</code></pre>
<h3>My Janky Solution</h3>
<pre><code>$ sudo mv /usr/bin/lsb_release .
$ python3 -m pip check
No broken requirements found.

$ sudo python3 -m pip install django</code></pre>
<p>(success)</p>
{% endblock %}
